### PR TITLE
Stylus

### PR DESCRIPTION
**Pull request by astralarya**
Changes the CSS to use the Stylus preprocessor.  In addition, integrates the gulp.js build system.  Furthermore, uses gulp.js to deploy on gh-pages.

To collaborators: use `run.sh` to run the development http server while watching with gulp.js to automatically rebuild changed files.  This replaces the previous `node web.js` command.

This is a major change, integrating the gulp.js build system, therefore should bump the repo to version 0.3.0.  It will pave the way for js minification/concatenation, as well as cache busting, etc.

### CODE REVIEW

**Comment by sunderhaus** [comment]
#### Stylus

All right, what I was hoping to see from this commit was a change over to using full on Stylus. Correct me if I'm wrong, but Stylus supports dropping the semicolons and curly braces. Correct? Wouldn't we prefer to drop the braces and other fluff the Stylus team [seems to tout on their homepage](http://learnboost.github.io/stylus/)?

#### Gulp Tasks over Shell Scripts

Also, Gulp [recommends using tasks](https://github.com/gulpjs/gulp/blob/master/docs/CLI.md#tasks) to perform their tool's actions. Why do we even need the shell script? Shouldn't this all be possible with the Gulp tasks?

#### JS Conditional Brace Syntax

Where appropriately defined by the syntax of the file I'd like to encourage the correct use of braces. In the officials-list.js changes you performed, can you please update the if statements to use curly braces. I'd be more inclined to allow the white-space driven syntax if we were writing coffeescript, but we aren't.

**Comment by astralarya** [comment]
> Wouldn't we prefer to drop the braces and other fluff the Stylus team seems to tout on their homepage?

I kind of like the more CSS feel with the braces (they are optional).  I'm not completely sure which way I like better, since really I just wanted to get my hands on their [fancy library](http://axis.bitballoon.com/).  I'm fine with whatever you prefer.  (TODO?)

> Why do we even need the shell script? Shouldn't this all be possible with the Gulp tasks?

The secret: it _is_ all gulp tasks!  I guess I should make that clear in the docs  (DONE).  `run.sh` is just an idempotent button to make things "just work" after `git clone`.  Maybe we don't need it.

> can you please update the if statements to use curly braces

Yes! I prefer that.  Do we want to make this the project style guidelines?  I was just following the local style.  (DONE)

**Comment by sunderhaus** [comment]
I did see the gulp tasks within the shell script which just led me to running the gulp tasks after installing globally :) Nice touch with the live reload. I think we'll need to include a development/production distinction in the minification and compilation of static assets at some point. That all looks good.

I'm all for merging this once the error I'm seeing from line 46 in map.js gets cleaned up. Looks like it's referring to the prev_color when it's never defined. What's that used for? The state last highlighted?

**Comment by astralarya** [comment]
DONE.  The error in map.js was a refactoring artifact. bleh.

I also changed the host to automatically open the webpage at `locahost.citizen.com` to make starting editing easier.  The erroneous code in `map.js` actually never executed unless the geolocation call fails.

**Comment by sunderhaus** [comment]
Looks good. 404 on the Reps page is unrelated to this changeset.

Well done, Mara.

**Pull request closed without merging**
